server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /_astro/ {
        expires max;
        add_header Cache-Control "public, immutable";
    }

    location ~* \.html$ {
        add_header Cache-Control "no-cache";
    }

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }
}
